const express=require('express'),path=require('path'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),{Pool}=require('pg');
const app=express();app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const seed=[['Blush Peony','bouquet',590000,'BESTSELLER','p1','✿'],['Garden Morning','bouquet',690000,'NEW','p2','❀'],['Rosé Muse','box',790000,'','p3','✽'],['Wild & Warm','bouquet',620000,'','p4','❁'],['Green Whisper','bouquet',540000,'','p5','✿'],['Peach Letter','gift',850000,'GIFT SET','p6','❀'],['Lavender Dream','box',720000,'','p7','✽'],['Sunday Picnic','gift',980000,'PREMIUM','p8','❁']];
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,price INTEGER NOT NULL,badge TEXT DEFAULT '',class_name TEXT DEFAULT '',symbol TEXT DEFAULT '✿',active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT now());CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,order_code TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,note TEXT DEFAULT '',items JSONB NOT NULL,total INTEGER NOT NULL,status TEXT DEFAULT 'new',created_at TIMESTAMPTZ DEFAULT now());CREATE TABLE IF NOT EXISTS admins(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now());`);if(+(await pool.query('SELECT COUNT(*) c FROM products')).rows[0].c===0)for(const p of seed)await pool.query('INSERT INTO products(name,category,price,badge,class_name,symbol) VALUES($1,$2,$3,$4,$5,$6)',p);if(+(await pool.query('SELECT COUNT(*) c FROM admins')).rows[0].c===0){const e=process.env.ADMIN_EMAIL||'admin@bloomora.local',p=process.env.ADMIN_PASSWORD||'Bloomora123!';await pool.query('INSERT INTO admins(email,password_hash) VALUES($1,$2)',[e,await bcrypt.hash(p,12)]);}}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),process.env.JWT_SECRET||'change-me-in-production');next()}catch(e){res.status(401).json({error:'Unauthorized'})}}
app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:true})}catch(e){res.status(503).json({ok:false,database:false})}});
app.get('/api/products',async(req,res)=>res.json((await pool.query('SELECT id,name,category,price,badge,class_name cls,symbol FROM products WHERE active=true ORDER BY id')).rows));
app.post('/api/orders',async(req,res)=>{const{customerName,phone,address,note='',items}=req.body;if(!customerName||!phone||!address||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Thiếu thông tin đơn hàng'});const ids=items.map(x=>Number(x.id));const ps=(await pool.query('SELECT id,name,price FROM products WHERE active=true AND id=ANY($1::int[])',[ids])).rows,map=new Map(ps.map(p=>[p.id,p]));let total=0,n=[];for(const x of items){const p=map.get(Number(x.id)),qty=Math.max(1,Math.min(99,Number(x.qty)||1));if(!p)return res.status(400).json({error:'Sản phẩm không hợp lệ'});total+=p.price*qty;n.push({id:p.id,name:p.name,price:p.price,qty})}const code='BL-'+Date.now().toString().slice(-8);const r=await pool.query('INSERT INTO orders(order_code,customer_name,phone,address,note,items,total) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING order_code,total,status,created_at',[code,customerName,phone,address,note,JSON.stringify(n),total]);res.status(201).json({ok:true,order:r.rows[0]})});
app.post('/api/admin/login',async(req,res)=>{const r=await pool.query('SELECT * FROM admins WHERE email=$1',[req.body.email]);if(!r.rows[0]||!(await bcrypt.compare(req.body.password,r.rows[0].password_hash)))return res.status(401).json({error:'Email hoặc mật khẩu không đúng'});res.json({token:jwt.sign({id:r.rows[0].id,email:r.rows[0].email},process.env.JWT_SECRET||'change-me-in-production',{expiresIn:'12h'})})});
app.get('/api/admin/orders',auth,async(req,res)=>res.json((await pool.query('SELECT * FROM orders ORDER BY created_at DESC LIMIT 200')).rows));
app.patch('/api/admin/orders/:id',auth,async(req,res)=>{if(!['new','confirmed','delivering','completed','cancelled'].includes(req.body.status))return res.status(400).json({error:'Status không hợp lệ'});res.json((await pool.query('UPDATE orders SET status=$1 WHERE id=$2 RETURNING *',[req.body.status,req.params.id])).rows[0]||null)});
app.patch('/api/admin/products/:id',auth,async(req,res)=>res.json((await pool.query('UPDATE products SET active=$1 WHERE id=$2 RETURNING *',[!!req.body.active,req.params.id])).rows[0]||null));
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
const port=process.env.PORT||3000;init().then(()=>app.listen(port,'0.0.0.0',()=>console.log('Bloomora running on '+port))).catch(e=>{console.error(e);process.exit(1)});